name: Ping

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      COMMAND: |
        curl --verbose --silent --write-out '\n\n%{time_total} sec\n' $URL 2>&1
          | sed '/azurewebsites\.net/d'
          | perl -0pe 's/(?<=\/api\/)\S+/***/gm'
    steps:
      - name: for BL
        run: eval $COMMAND
        env:
          URL: ${{ secrets.API_ENDPOINT_BL }}
      - name: for NV
        run: eval $COMMAND
        env:
          URL: ${{ secrets.API_ENDPOINT_NV }}
